<a href="https://colab.research.google.com/github/santhoshBjeeffy/Pandas/blob/master/Filtering_sorting_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [3]:
euro12 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv', sep=',')
euro12

                   Team  Goals  ...  Subs off  Players Used
0               Croatia      4  ...         9            16
1        Czech Republic      4  ...        11            19
2               Denmark      4  ...         7            15
3               England      5  ...        11            16
4                France      3  ...        11            19
5               Germany     10  ...        15            17
6                Greece      5  ...        12            20
7                 Italy      6  ...        18            19
8           Netherlands      2  ...         7            15
9                Poland      2  ...         7            17
10             Portugal      6  ...        14            16
11  Republic of Ireland      1  ...        10            17
12               Russia      5  ...         7            16
13                Spain     12  ...        17            18
14               Sweden      5  ...         9            18
15              Ukraine      2  ...         9            18

[16 rows x 35 columns]

In [6]:
#Select only goals column
euro12.Goals

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

In [7]:
#How many teams are participated in the euro12?
euro12.shape[0]

16

In [8]:
#what is the no of columns in the dataset
euro12.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [9]:
euro12.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
Team                          16 non-null object
Goals                         16 non-null int64
Shots on target               16 non-null int64
Shots off target              16 non-null int64
Shooting Accuracy             16 non-null object
% Goals-to-shots              16 non-null object
Total shots (inc. Blocked)    16 non-null int64
Hit Woodwork                  16 non-null int64
Penalty goals                 16 non-null int64
Penalties not scored          16 non-null int64
Headed goals                  16 non-null int64
Passes                        16 non-null int64
Passes completed              16 non-null int64
Passing Accuracy              16 non-null object
Touches                       16 non-null int64
Crosses                       16 non-null int64
Dribbles                      16 non-null int64
Corners Taken                 16 non-null int64
Tackles                       16 non-null int64
Clearances                    16 non-null int64
Interceptions                 16 non-null int64
Clearances off line           15 non-null float64
Clean Sheets                  16 non-null int64
Blocks                        16 non-null int64
Goals conceded                16 non-null int64
Saves made                    16 non-null int64
Saves-to-shots ratio          16 non-null object
Fouls Won                     16 non-null int64
Fouls Conceded                16 non-null int64
Offsides                      16 non-null int64
Yellow Cards                  16 non-null int64
Red Cards                     16 non-null int64
Subs on                       16 non-null int64
Subs off                      16 non-null int64
Players Used                  16 non-null int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

View only the columns Team,Yellow cards and red cards and assign them to a dataframe called discipline

In [12]:
discipline=euro12[['Team','Yellow Cards','Red Cards']]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

sort the teams by red card then to yellow cards

In [14]:
discipline.sort_values(['Red Cards','Yellow Cards'],ascending=False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

Calculate the mean yellow cards given per team

In [15]:
round(discipline['Yellow Cards'].mean())

7

#Filter teams that scored more than 5 goals

In [16]:
euro12[euro12.Goals > 5]

        Team  Goals  Shots on target  ...  Subs on Subs off Players Used
5    Germany     10               32  ...       15       15           17
7      Italy      6               34  ...       18       18           19
10  Portugal      6               22  ...       14       14           16
13     Spain     12               42  ...       17       17           18

[4 rows x 35 columns]

# select the team that starts with G

In [17]:
euro12[euro12.Team.str.startswith('G')]

      Team  Goals  Shots on target  ...  Subs on Subs off Players Used
5  Germany     10               32  ...       15       15           17
6   Greece      5                8  ...       12       12           20

[2 rows x 35 columns]

In [19]:
#Select the first 7 columns
euro12.iloc[:, 0:7]

                   Team  Goals  ...  % Goals-to-shots  Total shots (inc. Blocked)
0               Croatia      4  ...             16.0%                          32
1        Czech Republic      4  ...             12.9%                          39
2               Denmark      4  ...             20.0%                          27
3               England      5  ...             17.2%                          40
4                France      3  ...              6.5%                          65
5               Germany     10  ...             15.6%                          80
6                Greece      5  ...             19.2%                          32
7                 Italy      6  ...              7.5%                         110
8           Netherlands      2  ...              4.1%                          60
9                Poland      2  ...              5.2%                          48
10             Portugal      6  ...              9.3%                          82
11  Republic of Ireland      1  ...              5.2%                          28
12               Russia      5  ...             12.5%                          59
13                Spain     12  ...             16.0%                         100
14               Sweden      5  ...             13.8%                          39
15              Ukraine      2  ...              6.0%                          38

[16 rows x 7 columns]

#select all the columns except last 4

In [21]:
euro12.iloc[:,:-4]

                   Team  Goals  ...  Offsides  Yellow Cards
0               Croatia      4  ...         2             9
1        Czech Republic      4  ...         8             7
2               Denmark      4  ...         8             4
3               England      5  ...         6             5
4                France      3  ...         5             6
5               Germany     10  ...        12             4
6                Greece      5  ...        12             9
7                 Italy      6  ...        16            16
8           Netherlands      2  ...         3             5
9                Poland      2  ...         3             7
10             Portugal      6  ...        10            12
11  Republic of Ireland      1  ...        11             6
12               Russia      5  ...         4             6
13                Spain     12  ...        19            11
14               Sweden      5  ...         7             7
15              Ukraine      2  ...         4             5

[16 rows x 31 columns]

#Present only the shooting accuracy form england,italy and Russia

In [25]:
euro12.loc[euro12.Team.isin(['England','Italy','Russia']),['Team','Shooting Accuracy']]   #particular column

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%

In [26]:
euro12[euro12.Team == 'England']  #complete columns for particular row

      Team  Goals  Shots on target  ...  Subs on Subs off Players Used
3  England      5               11  ...       11       11           16

[1 rows x 35 columns]